### ISSUE TITLE
404 error on status-json.xsl

### ISSUE THREAD

**Issue by RadioCLaB** [moul/docker-icecast#16]
Hey, I reach a 404 error when I try to access to http://streamurl.fr/status-json.xsl:

> 404 - Could not parse XSLT file

In the error log I get this line:

> [2020-09-10  13:08:25] EROR xslt/xslt_transform problem reading stylesheet "/etc/icecast2/web/status-json.xsl"

And sometimes there is more errors before:

> [2020-09-10  13:03:28] WARN  I/O 
> [2020-09-10  13:03:28] WARN  warning : 
> [2020-09-10  13:03:28] WARN  failed to load external entity "/etc/icecast2/web/xml2json.xslt"
> [2020-09-10  13:03:28] WARN  compilation error: file /etc/icecast2/web/status-json.xsl line 2 element import
> [2020-09-10  13:03:28] WARN  xsl:import : unable to load /etc/icecast2/web/xml2json.xslt
> [2020-09-10  13:03:28] EROR xslt/xslt_transform problem reading stylesheet "/etc/icecast2/web/status-json.xsl"

I tried to make a symbolic link of `/usr/share/icecast2/web/xml2json.xslt` in `/etc/icecast2/web/xml2json.xslt` but still no change.
The config I use is the same that I previously used on a dedicated icecast server and it worked well.

Any idea ?

**Comment by moul** [comment]
Hi,

I don't know what are those files, do you have an example (screenshot) of the expected result on a non-dockerized server so I can give a look?

**Comment by RadioCLaB** [comment]
Hey,

Sorry I forgot to update my comment. I fixed it "magically" by copying the file to another name and rename it to original name.

> cp /etc/icecast2/web/status-json.xsl /etc/icecast2/web/status-json2.xsl
> rm /etc/icecast2/web/status-json.xsl
> mv /etc/icecast2/web/status-json2.xsl /etc/icecast2/web/status-json.xsl

It's probably a permissions issue (even if I changed the owner and tried to change chmod to 777 before)

Here's the result: http://stream.c-lab.fr:8001/status-json.xsl

Useful to save history of listeners count for example, or monitor the service.

**Comment by moul** [comment]
ok thx for the comment,

I just checked on my own dockerized instances of icecast and I've no issue displaying this page, so my ideas:

* something specific to your system (very rare when using docker)
* we don't use the same version (I rarely update the image on my server, maybe a newer version broke the thing)

---

if someone else has a related issue, please open a new issue and link back to this one, thx
